{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "e0ca5a22",
   "metadata": {},
   "source": [
    "### Áreas da Inteligência Artificial \n",
    "\n",
    "> Sistemas Especialistas\n",
    "> Visão Computacional\n",
    "> Machine Learning (_métodos matemáticos para treinar algoritmos_)\n",
    "> Processamento de linguagem Natural\n",
    "> Algoritmos Genéricos\n",
    "> Sistemas Multiagente\n",
    "> Mineração de dados\n",
    "> Resolução de problemas por meio de busca\n",
    "> Lógica Fuzzy\n",
    "> Raciocínio baseado em casos\n",
    "> Redes Neurias\n",
    "> Robótica\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "268a9f01",
   "metadata": {},
   "source": [
    "### Métodos Preditivos\n",
    "#### Previsão\n",
    "<br />\n",
    "\n",
    "- Classificação (Rótulos) => Defini classes : Mark Direto, Insatisfação de clientes, Risco de Crédito, Filtros de SPAM, Separação de Notícias, Reconhecimento de Voz, Reconhecimento Facial, _**Previsão de Doenças**_ \n",
    "\n",
    "<br />\n",
    "\n",
    "- Regressão => Previsão de Valores Numéricos : Gastos de Propaganda, Velocidade do vento, Previsão do Valor de Dólar, **A probabilidade do paciente Viver**, Risco de Investimento, Limite de Cartão de Crédito, Novos valores dos produtos"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cb9fce9a",
   "metadata": {},
   "source": [
    "### Métodos Descritivos\n",
    "\n",
    "<br />\n",
    "\n",
    "- Associação : Regras de Associação (Mercado. Cervajas & Fraldas); Itens que são vendidos em conjuntos, Controle de Evasão de Universidades\n",
    "\n",
    "<br />\n",
    "\n",
    "- Agrupamento : Documentos e Notícias, Produtos Similares, Perfil de Clientes (Ex: Netflix), **Análise das Redes Sociais**\n",
    "\n",
    "<br />\n",
    "\n",
    "- Detecção de desvios : (_**OUTLIERS**_), Fraudes em cartão de crédito, Invasão de Redes, Consumo de Energia Elétrica, Desempenho de Atletas (**Doping**), Monitoramento de Máquinas em um Data Center\n",
    "\n",
    "<br />\n",
    "\n",
    "- Padrões sequenciais : Livrarias, Mark Direcionado, **Prevensão de Doenças**, Navegação de Sites.\n",
    "\n",
    "<br />\n",
    "\n",
    "- Sumarização : Perfil de pessoas, Sequementação de Mercado"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f6868f29",
   "metadata": {},
   "source": [
    "### Tipos de Aprendizagem de Máquina\n",
    "##### Pesquisar como funciona a aprendizagem de máquina e como elas se diferenciam uma das outras\n",
    "\n",
    "<br />\n",
    "\n",
    "- Supervisionada >> Métodos Preditivos (Definição de **classes** gerando um modelo aprendido)\n",
    "\n",
    "<br />\n",
    "\n",
    "- Não Supervisionada >> Métodos Descritivos\n",
    "\n",
    "<br />\n",
    "\n",
    "- Reforço (Sist Multi Agente, SMA)\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "249efbd1",
   "metadata": {},
   "source": [
    "### CLASSIFICAÇÃO\n",
    "\n",
    "- Atributos Previsões > Meta/Classe\n",
    "- Valor do Atributo Meta é **Conhecido** >>> Aprendizagem Supervisionada"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8d37c4bb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Sexo</th>\n",
       "      <th>País</th>\n",
       "      <th>Idade</th>\n",
       "      <th>Comprar</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>M</td>\n",
       "      <td>França</td>\n",
       "      <td>25</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>F</td>\n",
       "      <td>Inglaterra</td>\n",
       "      <td>30</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>F</td>\n",
       "      <td>Brasil</td>\n",
       "      <td>32</td>\n",
       "      <td>N</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>M</td>\n",
       "      <td>França</td>\n",
       "      <td>26</td>\n",
       "      <td>N</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>F</td>\n",
       "      <td>Itália</td>\n",
       "      <td>27</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>M</td>\n",
       "      <td>Espanha</td>\n",
       "      <td>28</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>M</td>\n",
       "      <td>Peru</td>\n",
       "      <td>15</td>\n",
       "      <td>N</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>M</td>\n",
       "      <td>Chile</td>\n",
       "      <td>10</td>\n",
       "      <td>N</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>F</td>\n",
       "      <td>Japão</td>\n",
       "      <td>22</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>F</td>\n",
       "      <td>Inglaterra</td>\n",
       "      <td>32</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>F</td>\n",
       "      <td>Uruguai</td>\n",
       "      <td>70</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>M</td>\n",
       "      <td>México</td>\n",
       "      <td>55</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Sexo        País  Idade Comprar\n",
       "0     M      França     25       S\n",
       "1     F  Inglaterra     30       S\n",
       "2     F      Brasil     32       N\n",
       "3     M      França     26       N\n",
       "4     F      Itália     27       S\n",
       "5     M     Espanha     28       S\n",
       "6     M        Peru     15       N\n",
       "7     M       Chile     10       N\n",
       "8     F       Japão     22       S\n",
       "9     F  Inglaterra     32       S\n",
       "10    F     Uruguai     70       S\n",
       "11    M      México     55       S"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# criando um dicionário de compra de livros\n",
    "import pandas as pd\n",
    "pHistorico = {\n",
    "    \"Sexo\" : ['M', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'F', 'F', 'M'],\n",
    "    \"País\" : ['França', 'Inglaterra', 'Brasil', 'França', 'Itália', 'Espanha', \n",
    "              'Peru', 'Chile', 'Japão', 'Inglaterra', 'Uruguai', 'México'],\n",
    "    'Idade' : [25, 30, 32, 26, 27, 28, 15, 10, 22, 32, 70, 55], \n",
    "    'Comprar' : ['S','S', 'N', 'N', 'S', 'S', 'N', 'N', 'S', 'S', 'S', 'S']\n",
    "}\n",
    "\n",
    "pHistorico\n",
    "\n",
    "pd.DataFrame(pHistorico)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
